---
- name: Upgrade prod {{ COMPONENT }}
  hosts: prod
  gather_facts: False
  become_user: root
  become_method: sudo
  
  tasks:
    - name: Upgrade image number in {{ COMPONENT }}-deploy.yml
      become: True
      replace:
        dest: /usr/kubernetes/pip-services-content/{{ COMPONENT }}-deploy.yml
        regexp: 'image:(.)*'
        replace: 'image: pipdevs/{{ COMPONENT }}:{{ VERSION }}-{{ BUILD_NUMBER }}'
    - name: Start rollout update
      raw: kubectl apply -f /usr/kubernetes/pip-services-content/{{ COMPONENT }}-deploy.yml --record